// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/aaa/aaa.proto

package aaa

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AAA_Ping_FullMethodName              = "/aaa.AAA/Ping"
	AAA_Login_FullMethodName             = "/aaa.AAA/Login"
	AAA_Register_FullMethodName          = "/aaa.AAA/Register"
	AAA_ValidateToken_FullMethodName     = "/aaa.AAA/ValidateToken"
	AAA_RefreshToken_FullMethodName      = "/aaa.AAA/RefreshToken"
	AAA_TrackSearch_FullMethodName       = "/aaa.AAA/TrackSearch"
	AAA_TrackComicView_FullMethodName    = "/aaa.AAA/TrackComicView"
	AAA_GetRecentSearches_FullMethodName = "/aaa.AAA/GetRecentSearches"
	AAA_GetRecentViews_FullMethodName    = "/aaa.AAA/GetRecentViews"
)

// AAAClient is the client API for AAA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Auth service provides authentication and token management operations
type AAAClient interface {
	// Ping checks if the service is available
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Login authenticates a user and returns access and refresh tokens
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Register creates a new user account
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// ValidateToken verifies if a token is valid and returns user information
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	// RefreshToken refreshes an expired access token using a refresh token
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	TrackSearch(ctx context.Context, in *TrackSearchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	TrackComicView(ctx context.Context, in *TrackComicViewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetRecentSearches(ctx context.Context, in *GetRecentSearchesRequest, opts ...grpc.CallOption) (*GetRecentSearchesResponse, error)
	GetRecentViews(ctx context.Context, in *GetRecentViewsRequest, opts ...grpc.CallOption) (*GetRecentViewsResponse, error)
}

type aAAClient struct {
	cc grpc.ClientConnInterface
}

func NewAAAClient(cc grpc.ClientConnInterface) AAAClient {
	return &aAAClient{cc}
}

func (c *aAAClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AAA_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aAAClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AAA_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aAAClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AAA_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aAAClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, AAA_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aAAClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, AAA_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aAAClient) TrackSearch(ctx context.Context, in *TrackSearchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AAA_TrackSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aAAClient) TrackComicView(ctx context.Context, in *TrackComicViewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AAA_TrackComicView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aAAClient) GetRecentSearches(ctx context.Context, in *GetRecentSearchesRequest, opts ...grpc.CallOption) (*GetRecentSearchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecentSearchesResponse)
	err := c.cc.Invoke(ctx, AAA_GetRecentSearches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aAAClient) GetRecentViews(ctx context.Context, in *GetRecentViewsRequest, opts ...grpc.CallOption) (*GetRecentViewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecentViewsResponse)
	err := c.cc.Invoke(ctx, AAA_GetRecentViews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AAAServer is the server API for AAA service.
// All implementations must embed UnimplementedAAAServer
// for forward compatibility.
//
// Auth service provides authentication and token management operations
type AAAServer interface {
	// Ping checks if the service is available
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Login authenticates a user and returns access and refresh tokens
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Register creates a new user account
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// ValidateToken verifies if a token is valid and returns user information
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	// RefreshToken refreshes an expired access token using a refresh token
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	TrackSearch(context.Context, *TrackSearchRequest) (*emptypb.Empty, error)
	TrackComicView(context.Context, *TrackComicViewRequest) (*emptypb.Empty, error)
	GetRecentSearches(context.Context, *GetRecentSearchesRequest) (*GetRecentSearchesResponse, error)
	GetRecentViews(context.Context, *GetRecentViewsRequest) (*GetRecentViewsResponse, error)
	mustEmbedUnimplementedAAAServer()
}

// UnimplementedAAAServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAAAServer struct{}

func (UnimplementedAAAServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAAAServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAAAServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAAAServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedAAAServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedAAAServer) TrackSearch(context.Context, *TrackSearchRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackSearch not implemented")
}
func (UnimplementedAAAServer) TrackComicView(context.Context, *TrackComicViewRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackComicView not implemented")
}
func (UnimplementedAAAServer) GetRecentSearches(context.Context, *GetRecentSearchesRequest) (*GetRecentSearchesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecentSearches not implemented")
}
func (UnimplementedAAAServer) GetRecentViews(context.Context, *GetRecentViewsRequest) (*GetRecentViewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecentViews not implemented")
}
func (UnimplementedAAAServer) mustEmbedUnimplementedAAAServer() {}
func (UnimplementedAAAServer) testEmbeddedByValue()             {}

// UnsafeAAAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AAAServer will
// result in compilation errors.
type UnsafeAAAServer interface {
	mustEmbedUnimplementedAAAServer()
}

func RegisterAAAServer(s grpc.ServiceRegistrar, srv AAAServer) {
	// If the following call pancis, it indicates UnimplementedAAAServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AAA_ServiceDesc, srv)
}

func _AAA_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AAAServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AAA_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AAAServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AAA_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AAAServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AAA_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AAAServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AAA_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AAAServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AAA_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AAAServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AAA_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AAAServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AAA_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AAAServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AAA_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AAAServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AAA_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AAAServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AAA_TrackSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AAAServer).TrackSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AAA_TrackSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AAAServer).TrackSearch(ctx, req.(*TrackSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AAA_TrackComicView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackComicViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AAAServer).TrackComicView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AAA_TrackComicView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AAAServer).TrackComicView(ctx, req.(*TrackComicViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AAA_GetRecentSearches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentSearchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AAAServer).GetRecentSearches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AAA_GetRecentSearches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AAAServer).GetRecentSearches(ctx, req.(*GetRecentSearchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AAA_GetRecentViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentViewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AAAServer).GetRecentViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AAA_GetRecentViews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AAAServer).GetRecentViews(ctx, req.(*GetRecentViewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AAA_ServiceDesc is the grpc.ServiceDesc for AAA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AAA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aaa.AAA",
	HandlerType: (*AAAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AAA_Ping_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AAA_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _AAA_Register_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _AAA_ValidateToken_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AAA_RefreshToken_Handler,
		},
		{
			MethodName: "TrackSearch",
			Handler:    _AAA_TrackSearch_Handler,
		},
		{
			MethodName: "TrackComicView",
			Handler:    _AAA_TrackComicView_Handler,
		},
		{
			MethodName: "GetRecentSearches",
			Handler:    _AAA_GetRecentSearches_Handler,
		},
		{
			MethodName: "GetRecentViews",
			Handler:    _AAA_GetRecentViews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/aaa/aaa.proto",
}
